export const basics = {
  head: ['type', 'raw', 'db', 'lite', 'ratio', 'abbr', 'eng', 'chs'], 
  rows: [
    ['string', 100, 100, 101, 101, 'date'     , 'date'                                     , '报告日期'           ], 
    ['number', 101, 101, 102, 102, 'eps'      , 'basic eps'                                , '基本每股收益'         ], 
    ['number', 102, 102, 103, 103, 'bvps'     , 'net assets per share'                     , '每股净资产'          ], 
    ['number', 103, 103, 104, 104, 'opCfps'   , 'operating cash flow per share'            , '每股经营活动产生的现金流量净额'], 
    ['number', 104, 104, 105, 105, 'opInc'    , 'operating income'                         , '主营业务收入'         ], 
    ['number', 105, 105, 106, 106, 'opPft'    , 'operating profit'                         , '主营业务利润'         ], 
    ['number', 106, 106, 107, 107, 'opPft'    , 'operating profit'                         , '营业利润'           ], 
    ['number', 107, 107, 108, 108, 'ivInc'    , 'investment income'                        , '投资收益'           ], 
    ['number', 108, 108, 109, 109, 'netNopInc', 'net non-operating income'                 , '营业外收支净额'        ], 
    ['number', 109, 109, 110, 110, 'pft'      , 'total profit'                             , '利润总额'           ], 
    ['number', 110, 110, 111, 111, 'netPft'   , 'net profit'                               , '净利润'            ], 
    ['number', 111, 111, NaN, NaN, 'netPft'   , 'net profit'                               , '净利润'            ], 
    ['number', 112, 112, NaN, NaN, 'netCfFrOp', 'net cash flow from operating activities'  , '经营活动产生的现金流量净额'  ], 
    ['number', 113, 113, NaN, NaN, 'netIcCce' , 'net increase in cash and cash equivalents', '现金及现金等价物净增加额'   ], 
    ['number', 114, 114, NaN, NaN, 'ast'      , 'total assets'                             , '总资产'            ], 
    ['number', 115, 115, NaN, NaN, 'curAst'   , 'current assets'                           , '流动资产'           ], 
    ['number', 116, 116, NaN, NaN, 'liab'     , 'total liabilities'                        , '总负债'            ], 
    ['number', 117, 117, NaN, NaN, 'curLiab'  , 'current liabilities'                      , '流动负债'           ], 
    ['number', 118, 118, NaN, NaN, 'eqtWoMin' , 'shareholders\' equity wo minority'        , '股东权益不含少数股东权益'   ], 
    ['number', 119, 119, 113, 113, 'wroe'     , 'weighted return on equity'                , '净资产收益率加权'       ], 
  ], 
}