export const basics = [
  ['报告日期', 'date'],
  ['基本每股收益', 'basic eps'],
  ['每股净资产', 'net assets per share'],
  ['每股经营活动产生的现金流量净额', 'net cash flow from operating activities per share'],
  ['主营业务收入', 'operating income'],
  ['主营业务利润', 'operating profit'],
  ['营业利润', 'operating profit'],
  ['投资收益', 'investment income'],
  ['营业外收支净额', 'net income outside the business'],
  ['利润总额', 'total profit'],
  ['净利润', 'net profit'],
  ['净利润', 'net profit'],
  ['经营活动产生的现金流量净额', 'net cash flow from operating activities'],
  ['现金及现金等价物净增加额', 'net increase in cash and cash equivalents'],
  ['总资产', 'total assets'],
  ['流动资产', 'current assets'],
  ['总负债', 'total liability'],
  ['流动负债', 'current liabilities'],
  ['股东权益不含少数股东权益', 'shareholders\' equity wo minority'],
  ['净资产收益率加权', 'return on equity weighted'],
]
