export const
  SYMBOL = 'symbol',
  CODE = 'code',
  NAME = 'name',
  DATE = 'date',
  SECTOR = 'sector',
  CONCEPT = 'concept',
  SECTORS = 'sectors',
  CONCEPTS = 'concepts',
  INDUSTRY = 'industry',
  AREA = 'area',
  EST = 'est',
  CHS = 'chs',
  ENG = 'eng',
  WEIGHT = 'weight',
  EXCHANGE = 'exchange'
