export const balances = [
  'symbol',
  'date',
  'Cash and cash equivalents',
  'Short-term investments',
  'Cash and short-term investments',
  'Receivables',
  'Inventories',
  'Total current assets',
  'Property, Plant & Equipment Net',
  'Goodwill and Intangible Assets',
  'Long-term investments',
  'Tax assets',
  'Total non-current assets',
  'Total assets',
  'Payables',
  'Short-term debt',
  'Total current liabilities',
  'Long-term debt',
  'Total debt',
  'Deferred revenue',
  'Tax Liabilities',
  'Deposit Liabilities',
  'Total non-current liabilities',
  'Total liabilities',
  'Other comprehensive income',
  'Retained earnings (deficit)',
  'Total shareholders equity',
  'Investments',
  'Net Debt',
  'Other Assets',
  'Other Liabilities',
]
