export const incomes = [
  'symbol',
  'date',
  'Revenue',
  'Revenue Growth',
  'Cost of Revenue',
  'Gross Profit',
  'R&D Expenses',
  'SG&A Expense',
  'Operating Expenses',
  'Operating Income',
  'Interest Expense',
  'Earnings before Tax',
  'Income Tax Expense',
  'Net Income - Non-Controlling int',
  'Net Income - Discontinued ops',
  'Net Income',
  'Preferred Dividends',
  'Net Income Com',
  'EPS',
  'EPS Diluted',
  'Weighted Average Shs Out',
  'Weighted Average Shs Out (Dil)',
  'Dividend per Share',
  'Gross Margin',
  'EBITDA Margin',
  'EBIT Margin',
  'Profit Margin',
  'Free Cash Flow margin',
  'EBITDA',
  'EBIT',
  'Consolidated Income',
  'Earnings Before Tax Margin',
  'Net Profit Margin',
]
