export const  generals = [
  [/ {2}/g, ' '],
  [/total/gi, 't'],
  [/other/gi, 'o'],
  [/from/gi, 'fr'],
  [/business/gi, 'b '],
  [/\band\b/gi, '&'],
  [/ & /gi, '&'],
  [/([ \-])term/gi, ' tm'],
  [/non([ \-])/gi, 'n-'],
  [/weighted([ \-])/gi, 'w '],
  [/average/gi, 'avg'],
  [/current/gi, 'cur'],
  [/asset(s?)/gi, 'ast'],
  [/income/gi, 'inc'],
  [/revenue/gi, 'rev'],
  [/purchase/gi, 'purc'],
  [/profit/gi, 'pft'],
  [/payment(s?)/gi, 'pm'],
  [/expens(es?)/gi, 'exp'],
  [/payable(s?)/gi, 'pyb'],
  [/financ(e|ial|ing)/gi, 'fin'],
  [/acquisition(s?)/gi, 'acq'],
  [/capital/gi, 'cap'],
  [/reserve/gi, 'rsv'],
  [/inventor(y|ies)/gi, 'invt'],
  [/invest(ing|ment(s?))/gi, 'iv'],
  [/interest(s?)/gi, 'intr'],
  [/insurance/gi, 'insr'],
  [/goodwill/gi, 'gdw'],
  [/intangible/gi, 'intg'],
  [/expenditure(s?)/gi, 'expd'],
  [/management/gi, 'mang'],
  [/dividend/gi, 'div'],
  [/deposit(s?)/gi, 'dps'],
  [/operating/gi, 'op'],
  [/receiv(ed|able(s?))/gi, 'recv'],
  [/liabilities/gi, 'liab'],
  [/estimated/gi, 'est'],
  [/unamortized/gi, 'un-amort'],
  [/due within one year/gi, 'dw1y'],
  [/attributable to/gi, 'attr '],
  [/cash (and|&) cash equivalents/gi, 'cce'],
]
