export const generals = [
  [/ {2}/g, ' '],
  [/the/g, ''],
  [/bank/gi, 'bk'],
  [/from/gi, 'fr'],
  [/other/gi, 'o'],
  [/sales/gi, 'sa'],
  [/to be/gi, 'tb'],
  [/fixed/gi, 'fx'],
  [/\b&\b/gi, ''],
  [/\bor\b/gi, ''],
  [/\band\b/gi, ''],
  [/\bbut\b/gi, ''],
  [/but not/gi, 'wo'],
  [/fees?/gi, 'fe'],
  [/fin ast/gi, 'fa'],
  [/profit/gi, 'pft'],
  [/equity/gi, 'eqt'],
  [/income/gi, 'inc'],
  [/average/gi, 'avg'],
  [/current/gi, 'cur'],
  [/revenue/gi, 'rev'],
  [/capital/gi, 'cap'],
  [/reserve/gi, 'rsv'],
  [/business/gi, 'b'],
  [/weighted/gi, 'w'],
  [/exchange/gi, 'ex'],
  [/loans?/gi, 'lo'],
  [/customer/gi, 'cu'],
  [/tax(es)?/gi, 'tx'],
  [/deferred/gi, 'def'],
  [/dividend/gi, 'div'],
  [/goodwill/gi, 'gdw'],
  [/original/gi, 'ori'],
  [/values?/gi, 'v'],
  [/cash flow/gi, 'cf'],
  [/preferred/gi, 'pref'],
  [/consolidated/gi, 'conso'],
  [/control(ling)?/gi, 'ctrl'],
  [/operating/gi, 'op'],
  [/assets?/gi, 'ast'],
  [/changes?/gi, 'ch'],
  [/open(ing?)/gi, 'o'],
  [/non([ \-])/gi, 'n'],
  [/premiums?/gi, 'prem'],
  [/deposits?/gi, 'dpo'],
  [/payments?/gi, 'pm'],
  [/payables?/gi, 'pyb'],
  [/expens(es?)/gi, 'exp'],
  [/estimated/gi, 'est'],
  [/insurance/gi, 'insr'],
  [/derivative/gi, 'deri'],
  [/intangible/gi, 'intg'],
  [/management/gi, 'mang'],
  [/recognized/gi, 'recg'],
  [/liabilities/gi, 'liab'],
  [/([ \-])term/gi, ' tm'],
  [/trad(e|ing)/gi, 't'],
  [/clos(e|ing)/gi, 'c'],
  [/real estate/gi, 're'],
  [/valuat(ion)?/gi, 'val'],
  [/materials?/gi, 'mat'],
  [/purchases?/gi, 'purc'],
  [/interests?/gi, 'intr'],
  [/net assets?/gi, 'bv'],
  [/depreciation/gi, 'depr'],
  [/central bank/gi, 'cbk'],
  [/discontinued/gi, 'disc'],
  [/balanc(e|ing)/gi, 'bal'],
  [/minorit(y|ies)/gi, 'min'],
  [/commissions?/gi, 'cms'],
  [/comprehensive/gi, 'compr'],
  [/compensations?/gi, 'compen'],
  [/weighted[ \-]/gi, 'w'],
  [/long[ \-]?term/gi, 'lt'],
  [/acquisitions?/gi, 'acq'],
  [/inventor(y|ies)/gi, 'invt'],
  [/expenditures?/gi, 'expd'],
  [/attributable to/gi, 'attr '],
  [/transaction(al)?/gi, 't'],
  [/short[ \-]term/gi, 'st'],
  [/shareholders'? ?/gi, ''],
  [/(sub)?total[ \-]/gi, ''],
  [/increase (in|of)/gi, 'ic'],
  [/decrease (in|of)/gi, 'dc'],
  [/advance(s?|ment?)/gi, 'adv'],
  [/financ(e|ial|ing)/gi, 'fin'],
  [/amortiz(ed|ation)/gi, 'amo'],
  [/borrow(ings?|ed)/gi, 'borw'],
  [/receiv(ed|ables?)/gi, 'recv'],
  [/invest(ing|ments?)/gi, 'iv'],
  [/product(ive?|ion?)/gi, 'prod'],
  [/dispos(ed|al|able)/gi, 'dsp'],
  [/due within one year/gi, 'dw1y'],
  [/financ(e|ial) assets?/gi, 'fa'],
  [/(services?)\s[a-zA-Z]+/gi, 'sv'],
  [/cash (and|&) cash equivalents/gi, 'cce'],
]
