export const incomes = {
  head: ['type', 'raw', 'db', 'lite', 'ratio', 'abbr', 'eng'], 
  rows: [
    ['string', 100, 100, 100, 100, 'symbol'       , 'symbol'                          ], 
    ['string', 100, 100, 100, 100, 'date'         , 'date'                            ], 
    ['number', 101, 101, 101, 101, 'rev'          , 'revenue'                         ], 
    ['number', 102, 102, 102, 102, 'revGrowth'    , 'revenue growth'                  ], 
    ['number', 200, 200, 200, 200, 'costOfRev'    , 'cost of revenue'                 ], 
    ['number', 210, 210, 210, 210, 'grossPft'     , 'gross profit'                    ], 
    ['number', 210, 210, 210, 210, 'rdExp'        , 'r&d expenses'                    ], 
    ['number', 210, 210, 210, 210, 'sgaExp'       , 'sg&a expense'                    ], 
    ['number', 210, 210, 210, 210, 'opExp'        , 'operating expenses'              ], 
    ['number', 210, 210, 210, 210, 'opInc'        , 'operating income'                ], 
    ['number', 210, 210, 210, 210, 'intrExp'      , 'interest expense'                ], 
    ['number', 400, 400, 400, 400, 'ebTx'         , 'earnings before tax'             ], 
    ['number', 220, 220, 220, 220, 'incTxExp'     , 'income tax expense'              ], 
    ['number', 301, 301, NaN, NaN, 'niNctrlInt'   , 'net income - non-controlling int'], 
    ['number', 302, 302, NaN, NaN, 'niDiscOps'    , 'net income - discontinued ops'   ], 
    ['number', 300, 300, 300, 300, 'ni'           , 'net income'                      ], 
    ['number', 630, 630, NaN, NaN, 'prefDivs'     , 'preferred dividends'             ], 
    ['number', 300, 300, 300, 300, 'niCom'        , 'net income com'                  ], 
    ['number', 600, 600, NaN, NaN, 'eps'          , 'eps'                             ], 
    ['number', 601, 601, NaN, NaN, 'epsDil'       , 'eps diluted'                     ], 
    ['number', 610, 610, NaN, NaN, 'wavgShsOut'   , 'weighted average shs out'        ], 
    ['number', 611, 611, NaN, NaN, 'wavgShsOutDil', 'weighted average shs out (dil)'  ], 
    ['number', 620, 620, NaN, NaN, 'divPerShare'  , 'dividend per share'              ], 
    ['number', 500, 500, NaN, NaN, 'grossMg'      , 'gross margin'                    ], 
    ['number', 501, 501, NaN, NaN, 'ebitdaMg'     , 'ebitda margin'                   ], 
    ['number', 502, 502, NaN, NaN, 'ebitMg'       , 'ebit margin'                     ], 
    ['number', 503, 503, NaN, NaN, 'pftMg'        , 'profit margin'                   ], 
    ['number', 504, 504, NaN, NaN, 'freeCfMg'     , 'free cash flow margin'           ], 
    ['number', 400, 400, 400, 400, 'ebitda'       , 'ebitda'                          ], 
    ['number', 400, 400, 400, 400, 'ebit'         , 'ebit'                            ], 
    ['number', 400, 400, 400, 400, 'consoInc'     , 'consolidated income'             ], 
    ['number', 505, 505, NaN, NaN, 'ebTxMg'       , 'earnings before tax margin'      ], 
    ['number', 506, 506, NaN, NaN, 'netPftMg'     , 'net profit margin'               ], 
  ], 
}