export const CodeToEng = {
  '300003': 'Lepu Medical Technology (Beijing) Co Ltd'                              ,
  '300015': 'Aier Eye Hospital Group Co Ltd'                                        ,
  '300017': 'Wangsu Science and Technology Co.,Ltd.'                                ,
  '300024': 'Siasun Robot & Automation Co Ltd'                                      ,
  '300033': 'Hithink Royalflush Information Network Co.,Ltd.'                       ,
  '300059': 'East Money Information Co Ltd'                                         ,
  '300070': 'Beijing Originwater Technology Co Ltd'                                 ,
  '300122': 'Chongqing Zhifei Biological Products Co Ltd'                           ,
  '300124': 'Shenzhen Inovance Technology Co Ltd'                                   ,
  '300136': 'Shenzhen Sunway Communication Co Ltd'                                  ,
  '300142': 'Walvax Biotechnology Co Ltd'                                           ,
  '300144': 'SONGCHENG PERFORMANCE DEVELOPMENT CO., LTD.'                           ,
  '300347': 'Hangzhou Tigermed Consulting Co., Ltd.'                                ,
  '300408': 'CHAOZHOU THREE-CIRCLE(GROUP)CO.,LTD'                                   ,
  '300413': 'Mango Excellent Media Co., Ltd.'                                       ,
  '300433': 'Lens Technology Co., Ltd.'                                             ,
  '300498': 'GUANGDONGWENSFOODSTUFFGROUPCO.,LTD'                                    ,
  '600000': 'Shanghai Pudong Development Bank Co Ltd'                               ,
  '600004': 'Guangzhou Baiyun International Airport Co Ltd'                         ,
  '600009': 'Shanghai International Airport Co Ltd'                                 ,
  '600010': 'Inner Mongolia Baotou Steel Union Co Ltd'                              ,
  '600011': 'Huaneng Power International Inc'                                       ,
  '600015': 'Hua Xia Bank Co Ltd'                                                   ,
  '600016': 'China Minsheng Banking Corp Ltd'                                       ,
  '600018': 'Shanghai International Port (Group) Co Ltd'                            ,
  '600019': 'Baoshan Iron &Steel Co Ltd'                                            ,
  '600023': 'Zhejiang Zheneng Electric Power Co., Ltd.'                             ,
  '600025': 'HuanengLancang River Hydropower Inc.'                                  ,
  '600027': 'Huadian Power International Corporation Ltd'                           ,
  '600028': 'China Petroleum & Chemical Corporation'                                ,
  '600029': 'China Southern Airlines Co Ltd'                                        ,
  '600030': 'CITIC Securities Co Ltd'                                               ,
  '600031': 'Sany Heavy Industry Co Ltd'                                            ,
  '600036': 'China Merchants Bank Co Ltd'                                           ,
  '600038': 'AVIC Helicopter Co.,Ltd.'                                              ,
  '600048': 'Poly Developments and Holdings Group Co., Ltd.'                        ,
  '600050': 'China United Network Communications Co Ltd'                            ,
  '600061': 'SDIC Capital Co., Ltd'                                                 ,
  '600066': 'Zhengzhou Yutong Bus Co Ltd'                                           ,
  '600068': 'China Gezhouba Group Co Ltd'                                           ,
  '600085': 'Beijing Tongrentang Co Ltd'                                            ,
  '600089': 'TBEA Co Ltd'                                                           ,
  '600100': 'Tsinghua Tongfang Co Ltd'                                              ,
  '600104': 'SAIC Motor Co Ltd'                                                     ,
  '600109': 'Sinolink Securities Co. Ltd.'                                          ,
  '600111': 'China Northern Rare Earth (Group) High-Tech Co.,Ltd'                   ,
  '600115': 'China Eastern Airlines Corp Ltd'                                       ,
  '600118': 'China Spacesat Co Ltd'                                                 ,
  '600153': 'Xiamen C&D Inc'                                                        ,
  '600170': 'Shanghai Construction Co Ltd'                                          ,
  '600176': 'CHINA JUSHI CO., LTD.'                                                 ,
  '600177': 'Youngor Group Co Ltd'                                                  ,
  '600183': 'Shengyi Technology Co.,Ltd.'                                           ,
  '600188': 'Yanzhou Coal Mining Co Ltd'                                            ,
  '600196': 'Shanghai Fosun Pharmaceutical (Group) Co Ltd'                          ,
  '600208': 'Xinhu Zhongbao Co Ltd'                                                 ,
  '600219': 'Shandong Nanshan Aluminium Co., Ltd.'                                  ,
  '600221': 'Hainan Airlines Holding Co., Ltd.'                                     ,
  '600233': 'YTO Express Group Co.,Ltd.'                                            ,
  '600271': 'Aisino Co.,Ltd'                                                        ,
  '600276': 'Jiangsu Hengrui Medicine Co Ltd'                                       ,
  '600297': 'China Grand Automotive Services Co., Ltd.'                             ,
  '600299': 'Bluestar Adisseo Company'                                              ,
  '600309': 'Wanhua Chemical Group Co., Ltd.'                                       ,
  '600332': 'GUANGZHOU BAIYUNSHAN PHARMACEUTICAL HOLDINGS COMPANY LIMITED'          ,
  '600340': 'China Fortune Land Development Co., Ltd.'                              ,
  '600346': 'Hengli Petrochemical Co.,Ltd.'                                         ,
  '600352': 'Zhejiang Longsheng Group Co Ltd'                                       ,
  '600362': 'Jiangxi Copper Co Ltd'                                                 ,
  '600369': 'Southwest Securities Co Ltd'                                           ,
  '600372': 'CHINA AVIONICS SYSTEMS CO.,LTD.'                                       ,
  '600383': 'Gemdale Corporation'                                                   ,
  '600390': 'Minmetals Capital Company Limited'                                     ,
  '600398': 'Heilan Home Co.,Ltd'                                                   ,
  '600406': 'NARI Technology Co., Ltd.'                                             ,
  '600436': 'Zhangzhou Pientzehuang Pharmaceutical Co Ltd'                          ,
  '600438': 'Tongwei Co Ltd'                                                        ,
  '600482': 'China Shipbuilding Industry Group Power Co.,Ltd'                       ,
  '600487': 'Hengtong Optic-Electric Co.,Ltd'                                       ,
  '600489': 'Zhongjin Gold Co Ltd'                                                  ,
  '600498': 'Fiberhome Telecommunication Technologies Co Ltd'                       ,
  '600516': 'Fangda Carbon New Material Co.,Ltd'                                    ,
  '600519': 'Kweichow Moutai Co Ltd'                                                ,
  '600522': 'Jiangsu Zhongtian Technologies Co Ltd'                                 ,
  '600535': 'TASLY PHARMACEUTICAL GROUP CO.,LTD'                                    ,
  '600547': 'Shandong Gold-Mining Co Ltd'                                           ,
  '600566': 'HUBEI JUMPCAN PHARMACEUTICAL CO., LTD.'                                ,
  '600570': 'Hundsun Technologies Inc.'                                             ,
  '600583': 'Offshore Oil Engineering Co Ltd'                                       ,
  '600585': 'Anhui Conch Cement Co Ltd'                                             ,
  '600588': 'Yonyou Network Technology Co., Ltd.'                                   ,
  '600606': 'Greenland Holdings Corporation Limited'                                ,
  '600637': 'Shanghai Oriental Pearl Media Co., Ltd.'                               ,
  '600655': 'SHANGHAI YUYUAN TOURIST MART (GROUP) CO., LTD.'                        ,
  '600660': 'Fuyao Glass Industry Group Co.,Ltd'                                    ,
  '600663': 'Shanghai Lujiazui Finance and Trade Zone Development Co Ltd'           ,
  '600674': 'Sichuan Chuantou Energy Co Ltd'                                        ,
  '600690': 'Haier Smart Home Co., Ltd.'                                            ,
  '600703': 'Sanan Optoelectronics Co.,Ltd'                                         ,
  '600705': 'AVIC CAPITAL CO.,LTD.'                                                 ,
  '600733': 'BAIC BluePark New Energy Technology Co.,Ltd'                           ,
  '600741': 'HUAYU Automotive Systems Company Limited'                              ,
  '600760': 'AVIC SHENYANG AIRCRAFT COMPANY LIMITED'                                ,
  '600795': 'GD Power Development Co Ltd'                                           ,
  '600809': 'Shanxi Xinghuacun Fen Wine Factory Co Ltd'                             ,
  '600816': 'Anxin Trust Co., Ltd'                                                  ,
  '600837': 'Haitong Securities Company Limited'                                    ,
  '600848': 'Shanghai Lingang Holdings Corporation Limited'                         ,
  '600867': 'Tonghua Dongbao Pharmaceutical Co.,Ltd.'                               ,
  '600886': 'SDIC Power Holdings Co.,Ltd.'                                          ,
  '600887': 'Inner Mongolia Yili Industrial Group Co Ltd'                           ,
  '600893': 'AVIC AVIATION ENGINE CORPORATION PLC.'                                 ,
  '600900': 'China Yangtze Power Co Ltd'                                            ,
  '600919': 'Bank of Jiangsu Co., Ltd'                                              ,
  '600926': 'BANK OF HANGZHOU CO., LTD'                                             ,
  '600928': 'BANK OF XI\'AN CO., LTD.'                                              ,
  '600958': 'ORIENT SECURITIES COMPANY LIMITED'                                     ,
  '600968': 'CNOOC Energy Technology & Services Limited'                            ,
  '600977': 'CHINA FILM CO., LTD.'                                                  ,
  '600989': 'Ningxia Baofeng Energy Group Co., Ltd.'                                ,
  '600998': 'Jointown Pharmaceutical Group Co Ltd'                                  ,
  '600999': 'China Merchants Securities Co Ltd'                                     ,
  '601006': 'Daqin Railway Co Ltd'                                                  ,
  '601009': 'Bank of Nanjing Co Ltd'                                                ,
  '601012': 'Longi Green Energy Technology Co., Ltd.'                               ,
  '601018': 'Ningbo Port Co Ltd'                                                    ,
  '601021': 'Spring Airlines Co., Ltd.'                                             ,
  '601066': 'China Securities Co., Ltd.'                                            ,
  '601088': 'China Shenhua Energy Co Ltd'                                           ,
  '601108': 'CAITONG SECURITIES CO.,LTD.'                                           ,
  '601111': 'Air China Ltd'                                                         ,
  '601117': 'China National Chemical Engineering Co Ltd'                            ,
  '601138': 'Foxconn Industrial Internet Co., Ltd.'                                 ,
  '601155': 'Future Land Holdings Co., Ltd.'                                        ,
  '601162': 'TIANFENG SECURITIES CO., LTD.'                                         ,
  '601166': 'Industrial Bank'                                                       ,
  '601169': 'Bank of Beijing Co Ltd'                                                ,
  '601186': 'China Railway Construction Co Ltd'                                     ,
  '601198': 'DONGXING SECURITIES CO., LTD.'                                         ,
  '601211': 'Guotai Junan Securities Co., Ltd.'                                     ,
  '601212': 'Baiyin Nonferrous Group Co., Ltd.'                                     ,
  '601216': 'Inner Mongolia Junzheng Energy & Chemical Group Co.,Ltd.'              ,
  '601225': 'Shaanxi Coal Industry Company Limited'                                 ,
  '601229': 'Bank of Shanghai Co., Ltd.'                                            ,
  '601236': 'HONGTA SECURITIES CO., LTD.'                                           ,
  '601238': 'Guangzhou Automobile Group Co., Ltd.'                                  ,
  '601288': 'Agricultural Bank of China Co Ltd'                                     ,
  '601298': 'Qingdao Port International Co., Ltd'                                   ,
  '601318': 'Ping An Insurance (Group) Company of China Ltd'                        ,
  '601319': 'The People\'s Insurance Company (Group) of China Limited'              ,
  '601328': 'Bank of Communications Co LTD'                                         ,
  '601336': 'New China Life Insurance Co Ltd'                                       ,
  '601360': '360 Security Technology Inc.'                                          ,
  '601377': 'Industrial Securities Co Ltd'                                          ,
  '601390': 'China Railway Group Limited'                                           ,
  '601398': 'Industrial and Commercial Bank of China Ltd'                           ,
  '601555': 'Soochow Securities Co Ltd'                                             ,
  '601577': 'BANK OF CHANGSHA CO., LTD.'                                            ,
  '601600': 'Aluminum Corporation of China Limited'                                 ,
  '601601': 'China Pacific Insurance (Group) Co Ltd'                                ,
  '601607': 'Shanghai Pharmaceuticals Holding Co.,Ltd'                              ,
  '601618': 'Metallurgical Corporation of China Co Ltd'                             ,
  '601628': 'China Life Insurance Company Limited'                                  ,
  '601633': 'Great Wall Motor Co Ltd'                                               ,
  '601668': 'China State Construction Engineering Co Ltd'                           ,
  '601669': 'Power Construction Corporation of China,Ltd'                           ,
  '601688': 'Huatai Securities Co Ltd'                                              ,
  '601698': 'China Satellite Communications Co.,Ltd.'                               ,
  '601727': 'Shanghai Electric Group Co Ltd'                                        ,
  '601766': 'CRRC Corporation Limited'                                              ,
  '601788': 'Everbright Securities Co Ltd'                                          ,
  '601800': 'China Communications Construction Company Limited'                     ,
  '601808': 'China Oilfield Services Limited'                                       ,
  '601818': 'China Everbright Bank Co Ltd'                                          ,
  '601828': 'Red Star Macalline Group Corporation Ltd.'                             ,
  '601838': 'BANK OF CHENGDU CO., LTD.'                                             ,
  '601857': 'PetroChina Co Ltd'                                                     ,
  '601877': 'Zhejiang Chint Electrics Co Ltd'                                       ,
  '601878': 'ZHESHANG SECURITIES CO., LTD.'                                         ,
  '601881': 'China Galaxy Securities Co., Ltd.'                                     ,
  '601888': 'China International Travel Service Co Ltd'                             ,
  '601898': 'China Coal Energy Co Ltd'                                              ,
  '601899': 'Zijin Mining Group Co Ltd'                                             ,
  '601901': 'Founder Securities Co Ltd'                                             ,
  '601919': 'COSCO SHIPPING Holdings Co., Ltd.'                                     ,
  '601933': 'Yonghui Superstores Co Ltd'                                            ,
  '601939': 'China Construction Bank'                                               ,
  '601985': 'China National Nuclear Power Co.,Ltd.'                                 ,
  '601988': 'Bank of China Ltd'                                                     ,
  '601989': 'China Shipbuilding Industry Co Ltd'                                    ,
  '601992': 'BBMG Corporation'                                                      ,
  '601997': 'Bank of Guiyang Co.,Ltd.'                                              ,
  '601998': 'China Citic Bank Corporation Limited'                                  ,
  '603019': 'Dawning Information Industry Co., Ltd.'                                ,
  '603156': 'Hebei Yangyuan ZhiHui Beverage Co., Ltd.'                              ,
  '603160': 'Shenzhen Huiding Technology Co., Ltd.'                                 ,
  '603259': 'WuXi AppTec Co., Ltd.'                                                 ,
  '603260': 'HOSHINE SILICON INDUSTRY CO.,LTD'                                      ,
  '603288': 'Foshan Haitian Flavouring and Food Company Ltd.'                       ,
  '603501': 'Will Semiconductor CO.,Ltd. Shanghai'                                  ,
  '603799': 'ZHEJIANG HUAYOU COBALT CO., LTD.'                                      ,
  '603833': 'Oppein Home Group Inc.'                                                ,
  '603899': 'SHANGHAI M&G STATIONERY INC.'                                          ,
  '603986': 'GigaDevice Semiconductor (Beijing) Inc.'                               ,
  '603993': 'China Molybdenum Co., Ltd.'                                            ,
  '000001': 'Ping An Bank Co., Ltd.'                                                ,
  '000002': 'China Vanke Co Ltd'                                                    ,
  '000063': 'ZTE Corporation'                                                       ,
  '000069': 'Shenzhen Overseas Chinese Town Co Ltd'                                 ,
  '000100': 'TCL Technology Group Corporation'                                      ,
  '000157': 'Zoomlion Heavy Industry Science & Technology Co Ltd'                   ,
  '000166': 'Shenwan Hongyuan Group CO., LTD'                                       ,
  '000333': 'Midea Group CO., LTD'                                                  ,
  '000338': 'Wei Chai Power Co Ltd'                                                 ,
  '000413': 'Dongxu Optoelectronic Technology Co., Ltd.'                            ,
  '000415': 'Bohai Leasing Co.,Ltd.'                                                ,
  '000423': 'Shandong Dong-Ee Jiao Co Ltd'                                          ,
  '000425': 'XCMG Construction Machinery Co Ltd'                                    ,
  '000538': 'Yunnan Baiyao Group Co., Ltd.'                                         ,
  '000568': 'Luzhou Lao Jiao Co Ltd'                                                ,
  '000596': 'Anhui Gujing Distillery Co Ltd'                                        ,
  '000625': 'Chongqing Changan Automobile Co Ltd'                                   ,
  '000627': 'Hubei Biocause Pharmaceutical Co Ltd'                                  ,
  '000629': 'Pangang Group Vanadium Titanium & Resources Co., Ltd.'                 ,
  '000630': 'Tongling Nonferrous Metals Group Co. Ltd'                              ,
  '000651': 'Gree Electric Appliances,Inc. of Zhuhai'                               ,
  '000656': 'Jinke Property Group Co.,Ltd.'                                         ,
  '000661': 'Chang Chun High and New Technology Industry (Group) Inc.'              ,
  '000671': 'Sunshine City Group Co., Ltd.'                                         ,
  '000703': 'Hengyi Petrochemical Co Ltd'                                           ,
  '000709': 'HESTEEL COMPANY LIMITED'                                               ,
  '000723': 'Shanxi Meijin Energy Co.,Ltd.'                                         ,
  '000725': 'BOE Technology Group Co Ltd'                                           ,
  '000728': 'Guoyuan Securities Company Limited'                                    ,
  '000768': 'Avic Aircraft Co.,Ltd.'                                                ,
  '000776': 'GF Securities Co., Ltd.'                                               ,
  '000783': 'Changjiang Securities Company Limited'                                 ,
  '000786': 'Beijing New Building Materials Public Ltd Co'                          ,
  '000858': 'Wuliangye Yibin Co Ltd'                                                ,
  '000876': 'NEW HOPE LIUHE CO., LTD'                                               ,
  '000895': 'Henan Shuanghui Investment & Development Co Ltd'                       ,
  '000898': 'Angang Steel Co Ltd'                                                   ,
  '000938': 'Unisplendour Co., Ltd.'                                                ,
  '000961': 'Jiangsu Zhongnan Construction Group Co.,Ltd'                           ,
  '000963': 'Huadong Medicine Co Ltd'                                               ,
  '001979': 'CHINA MERCHANTS SHEKOU INDUSTRIAL ZONE HOLDINGS CO.,LTD'               ,
  '002001': 'Zhejiang NHU Co Ltd'                                                   ,
  '002007': 'Hualan Biological Engineering INC'                                     ,
  '002008': 'Han\'s Laser Technology Industry Group Co., Ltd.'                      ,
  '002010': 'Transfar Zhilian Co.,Ltd.'                                             ,
  '002024': 'SUNING.COM CO.,LTD.'                                                   ,
  '002027': 'Focus Media Information Technology Co., Ltd.'                          ,
  '002032': 'Zhejiang Supor Co.,Ltd'                                                ,
  '002044': 'Meinian Onehealth Healthcare Holdings Co., Ltd.'                       ,
  '002050': 'ZHEJIANG SANHUA INTELLIGENT CONTROLS CO.,LTD.'                         ,
  '002081': 'Suzhou Gold Mantis Construction Decoration Co Ltd'                     ,
  '002120': 'YUNDA Holding CO., Ltd.'                                               ,
  '002142': 'Bank of Ningbo Co Ltd'                                                 ,
  '002146': 'Risesun Real Estate Development Co Ltd'                                ,
  '002153': 'Beijing Shiji Information Technology Co Ltd'                           ,
  '002179': 'AVIC Jonhon Optronic Technology Co.,Ltd.'                              ,
  '002202': 'Xinjiang Goldwind Science & Technology Co Ltd'                         ,
  '002230': 'Iflytek Co.,Ltd.'                                                      ,
  '002236': 'Zhejiang Dahua Technology Co Ltd'                                      ,
  '002241': 'GoerTek Inc'                                                           ,
  '002252': 'Shanghai RAAS Blood Products Co Ltd'                                   ,
  '002271': 'Beijing Oriental Yuhong Waterproof Technology Co Ltd'                  ,
  '002294': 'Shenzhen Salubris Pharmaceuticals Co Ltd'                              ,
  '002304': 'Jiangsu Yanghe Brewery Joint-Stock Co Ltd'                             ,
  '002311': 'Guangdong Haid Group Co Ltd'                                           ,
  '002352': 'S.F. Holding Co., Ltd.'                                                ,
  '002410': 'Glodon Software Co Ltd'                                                ,
  '002411': 'YanAn Bicon Pharmaceutical Listed Company'                             ,
  '002415': 'Hangzhou Hikvision Digital Technology Co Ltd'                          ,
  '002422': 'Sichuan Kelun Pharmaceutical Co Ltd'                                   ,
  '002456': 'OFILM Group Co., Ltd.'                                                 ,
  '002460': 'Ganfeng Lithium Co Ltd'                                                ,
  '002466': 'Tianqi Lithium Industries, Inc.'                                       ,
  '002468': 'STO Express Co.,Ltd.'                                                  ,
  '002475': 'Luxshare Precision Industry Co., Ltd.'                                 ,
  '002493': 'Rongsheng Petro Chemical Co Ltd'                                       ,
  '002508': 'Hangzhou Robam Appliances Co Ltd'                                      ,
  '002555': 'WUHU SANQI INTERACTIVE ENTERTAINMENT NETWORK TECHNOLOGY GROUP CO.,LTD.',
  '002558': 'Giant Network Group Co., Ltd.'                                         ,
  '002594': 'BYD Co Ltd'                                                            ,
  '002601': 'Lomon Billions Group Co., Ltd.'                                        ,
  '002602': 'ZHEJIANG CENTURY HUATONG GROUP CO., LTD'                               ,
  '002607': 'Offcn Education Technology Co., Ltd.'                                  ,
  '002624': 'Perfect World Co., Ltd.'                                               ,
  '002673': 'WESTERN SECURITIES CO., LTD'                                           ,
  '002714': 'Muyuan Foodstuff Co., Ltd'                                             ,
  '002736': 'GUOSEN SECURITIES CO., LTD.'                                           ,
  '002739': 'WANDA FILM HOLDING CO., LTD'                                           ,
  '002773': 'Chengdu Kanghong Pharmaceutical Group Co., Ltd'                        ,
  '002841': 'Guangzhou Shiyuan Electronic Technology Company Limited'               ,
  '002916': 'Shennan Circuits Co., Ltd.'                                            ,
  '002938': 'Avary Holding (Shenzhen) Co., Limited'                                 ,
  '002939': 'CHINA GREAT WALL SECURITIES CO., LTD.'                                 ,
  '002945': 'ChinaLin Securities Co., Ltd.'                                         ,
  '002958': 'Qingdao Rural Commercial Bank Corporation'                             
}