export const c12ns = {
  head: ['symbol', 'chs', 'eng'], 
  rows: [
    ['300003', '乐普医疗'  , 'Lepu Medical Technology (Beijing) Co Ltd'                              ], 
    ['300015', '爱尔眼科'  , 'Aier Eye Hospital Group Co Ltd'                                        ], 
    ['300017', '网宿科技'  , 'Wangsu Science and Technology Co.,Ltd.'                                ], 
    ['300024', '机器人'   , 'Siasun Robot & Automation Co Ltd'                                      ], 
    ['300033', '同花顺'   , 'Hithink Royalflush Information Network Co.,Ltd.'                       ], 
    ['300059', '东方财富'  , 'East Money Information Co Ltd'                                         ], 
    ['300070', '碧水源'   , 'Beijing Originwater Technology Co Ltd'                                 ], 
    ['300122', '智飞生物'  , 'Chongqing Zhifei Biological Products Co Ltd'                           ], 
    ['300124', '汇川技术'  , 'Shenzhen Inovance Technology Co Ltd'                                   ], 
    ['300136', '信维通信'  , 'Shenzhen Sunway Communication Co Ltd'                                  ], 
    ['300142', '沃森生物'  , 'Walvax Biotechnology Co Ltd'                                           ], 
    ['300144', '宋城演艺'  , 'SONGCHENG PERFORMANCE DEVELOPMENT CO., LTD.'                           ], 
    ['300347', '泰格医药'  , 'Hangzhou Tigermed Consulting Co., Ltd.'                                ], 
    ['300408', '三环集团'  , 'CHAOZHOU THREE-CIRCLE(GROUP)CO.,LTD'                                   ], 
    ['300413', '快乐购'   , 'Mango Excellent Media Co., Ltd.'                                       ], 
    ['300433', '蓝思科技'  , 'Lens Technology Co., Ltd.'                                             ], 
    ['300498', '温氏股份'  , 'GUANGDONGWENSFOODSTUFFGROUPCO.,LTD'                                    ], 
    ['600000', '浦发银行'  , 'Shanghai Pudong Development Bank Co Ltd'                               ], 
    ['600004', '白云机场'  , 'Guangzhou Baiyun International Airport Co Ltd'                         ], 
    ['600009', '上海机场'  , 'Shanghai International Airport Co Ltd'                                 ], 
    ['600010', '包钢股份'  , 'Inner Mongolia Baotou Steel Union Co Ltd'                              ], 
    ['600011', '华能国际'  , 'Huaneng Power International Inc'                                       ], 
    ['600015', '华夏银行'  , 'Hua Xia Bank Co Ltd'                                                   ], 
    ['600016', '民生银行'  , 'China Minsheng Banking Corp Ltd'                                       ], 
    ['600018', '上港集团'  , 'Shanghai International Port (Group) Co Ltd'                            ], 
    ['600019', '宝钢股份'  , 'Baoshan Iron &Steel Co Ltd'                                            ], 
    ['600023', '浙能电力'  , 'Zhejiang Zheneng Electric Power Co., Ltd.'                             ], 
    ['600025', '华能水电'  , 'HuanengLancang River Hydropower Inc.'                                  ], 
    ['600027', '华电国际'  , 'Huadian Power International Corporation Ltd'                           ], 
    ['600028', '中国石化'  , 'China Petroleum & Chemical Corporation'                                ], 
    ['600029', '南方航空'  , 'China Southern Airlines Co Ltd'                                        ], 
    ['600030', '中信证券'  , 'CITIC Securities Co Ltd'                                               ], 
    ['600031', '三一重工'  , 'Sany Heavy Industry Co Ltd'                                            ], 
    ['600036', '招商银行'  , 'China Merchants Bank Co Ltd'                                           ], 
    ['600038', '中直股份'  , 'AVIC Helicopter Co.,Ltd.'                                              ], 
    ['600048', '保利地产'  , 'Poly Developments and Holdings Group Co., Ltd.'                        ], 
    ['600050', '中国联通'  , 'China United Network Communications Co Ltd'                            ], 
    ['600061', '国投资本'  , 'SDIC Capital Co., Ltd'                                                 ], 
    ['600066', '宇通客车'  , 'Zhengzhou Yutong Bus Co Ltd'                                           ], 
    ['600068', '葛洲坝'   , 'China Gezhouba Group Co Ltd'                                           ], 
    ['600085', '同仁堂'   , 'Beijing Tongrentang Co Ltd'                                            ], 
    ['600089', '特变电工'  , 'TBEA Co Ltd'                                                           ], 
    ['600100', '同方股份'  , 'Tsinghua Tongfang Co Ltd'                                              ], 
    ['600104', '上汽集团'  , 'SAIC Motor Co Ltd'                                                     ], 
    ['600109', '国金证券'  , 'Sinolink Securities Co. Ltd.'                                          ], 
    ['600111', '北方稀土'  , 'China Northern Rare Earth (Group) High-Tech Co.,Ltd'                   ], 
    ['600115', '东方航空'  , 'China Eastern Airlines Corp Ltd'                                       ], 
    ['600118', '中国卫星'  , 'China Spacesat Co Ltd'                                                 ], 
    ['600153', '建发股份'  , 'Xiamen C&D Inc'                                                        ], 
    ['600170', '上海建工'  , 'Shanghai Construction Co Ltd'                                          ], 
    ['600176', '中国巨石'  , 'CHINA JUSHI CO., LTD.'                                                 ], 
    ['600177', '雅戈尔'   , 'Youngor Group Co Ltd'                                                  ], 
    ['600183', '生益科技'  , 'Shengyi Technology Co.,Ltd.'                                           ], 
    ['600188', '兖州煤业'  , 'Yanzhou Coal Mining Co Ltd'                                            ], 
    ['600196', '复星医药'  , 'Shanghai Fosun Pharmaceutical (Group) Co Ltd'                          ], 
    ['600208', '新湖中宝'  , 'Xinhu Zhongbao Co Ltd'                                                 ], 
    ['600219', '南山铝业'  , 'Shandong Nanshan Aluminium Co., Ltd.'                                  ], 
    ['600221', '海航控股'  , 'Hainan Airlines Holding Co., Ltd.'                                     ], 
    ['600233', '圆通速递'  , 'YTO Express Group Co.,Ltd.'                                            ], 
    ['600271', '航天信息'  , 'Aisino Co.,Ltd'                                                        ], 
    ['600276', '恒瑞医药'  , 'Jiangsu Hengrui Medicine Co Ltd'                                       ], 
    ['600297', '广汇汽车'  , 'China Grand Automotive Services Co., Ltd.'                             ], 
    ['600299', '安迪苏'   , 'Bluestar Adisseo Company'                                              ], 
    ['600309', '万华化学'  , 'Wanhua Chemical Group Co., Ltd.'                                       ], 
    ['600332', '白云山'   , 'GUANGZHOU BAIYUNSHAN PHARMACEUTICAL HOLDINGS COMPANY LIMITED'          ], 
    ['600340', '华夏幸福'  , 'China Fortune Land Development Co., Ltd.'                              ], 
    ['600346', '恒力股份'  , 'Hengli Petrochemical Co.,Ltd.'                                         ], 
    ['600352', '浙江龙盛'  , 'Zhejiang Longsheng Group Co Ltd'                                       ], 
    ['600362', '江西铜业'  , 'Jiangxi Copper Co Ltd'                                                 ], 
    ['600369', '西南证券'  , 'Southwest Securities Co Ltd'                                           ], 
    ['600372', '中航电子'  , 'CHINA AVIONICS SYSTEMS CO.,LTD.'                                       ], 
    ['600383', '金地集团'  , 'Gemdale Corporation'                                                   ], 
    ['600390', '五矿资本'  , 'Minmetals Capital Company Limited'                                     ], 
    ['600398', '海澜之家'  , 'Heilan Home Co.,Ltd'                                                   ], 
    ['600406', '国电南瑞'  , 'NARI Technology Co., Ltd.'                                             ], 
    ['600436', '片仔癀'   , 'Zhangzhou Pientzehuang Pharmaceutical Co Ltd'                          ], 
    ['600438', '通威股份'  , 'Tongwei Co Ltd'                                                        ], 
    ['600482', '中国动力'  , 'China Shipbuilding Industry Group Power Co.,Ltd'                       ], 
    ['600487', '亨通光电'  , 'Hengtong Optic-Electric Co.,Ltd'                                       ], 
    ['600489', '中金黄金'  , 'Zhongjin Gold Co Ltd'                                                  ], 
    ['600498', '烽火通信'  , 'Fiberhome Telecommunication Technologies Co Ltd'                       ], 
    ['600516', '方大炭素'  , 'Fangda Carbon New Material Co.,Ltd'                                    ], 
    ['600519', '贵州茅台'  , 'Kweichow Moutai Co Ltd'                                                ], 
    ['600522', '中天科技'  , 'Jiangsu Zhongtian Technologies Co Ltd'                                 ], 
    ['600535', '天士力'   , 'TASLY PHARMACEUTICAL GROUP CO.,LTD'                                    ], 
    ['600547', '山东黄金'  , 'Shandong Gold-Mining Co Ltd'                                           ], 
    ['600566', '济川药业'  , 'HUBEI JUMPCAN PHARMACEUTICAL CO., LTD.'                                ], 
    ['600570', '恒生电子'  , 'Hundsun Technologies Inc.'                                             ], 
    ['600583', '海油工程'  , 'Offshore Oil Engineering Co Ltd'                                       ], 
    ['600585', '海螺水泥'  , 'Anhui Conch Cement Co Ltd'                                             ], 
    ['600588', '用友网络'  , 'Yonyou Network Technology Co., Ltd.'                                   ], 
    ['600606', '绿地控股'  , 'Greenland Holdings Corporation Limited'                                ], 
    ['600637', '东方明珠'  , 'Shanghai Oriental Pearl Media Co., Ltd.'                               ], 
    ['600655', '豫园股份'  , 'SHANGHAI YUYUAN TOURIST MART (GROUP) CO., LTD.'                        ], 
    ['600660', '福耀玻璃'  , 'Fuyao Glass Industry Group Co.,Ltd'                                    ], 
    ['600663', '陆家嘴'   , 'Shanghai Lujiazui Finance and Trade Zone Development Co Ltd'           ], 
    ['600674', '川投能源'  , 'Sichuan Chuantou Energy Co Ltd'                                        ], 
    ['600690', '青岛海尔'  , 'Haier Smart Home Co., Ltd.'                                            ], 
    ['600703', '三安光电'  , 'Sanan Optoelectronics Co.,Ltd'                                         ], 
    ['600705', '中航资本'  , 'AVIC CAPITAL CO.,LTD.'                                                 ], 
    ['600733', 'S*ST前锋', 'BAIC BluePark New Energy Technology Co.,Ltd'                           ], 
    ['600741', '华域汽车'  , 'HUAYU Automotive Systems Company Limited'                              ], 
    ['600760', '中航黑豹'  , 'AVIC SHENYANG AIRCRAFT COMPANY LIMITED'                                ], 
    ['600795', '国电电力'  , 'GD Power Development Co Ltd'                                           ], 
    ['600809', '山西汾酒'  , 'Shanxi Xinghuacun Fen Wine Factory Co Ltd'                             ], 
    ['600816', '安信信托'  , 'Anxin Trust Co., Ltd'                                                  ], 
    ['600837', '海通证券'  , 'Haitong Securities Company Limited'                                    ], 
    ['600848', '上海临港'  , 'Shanghai Lingang Holdings Corporation Limited'                         ], 
    ['600867', '通化东宝'  , 'Tonghua Dongbao Pharmaceutical Co.,Ltd.'                               ], 
    ['600886', '国投电力'  , 'SDIC Power Holdings Co.,Ltd.'                                          ], 
    ['600887', '伊利股份'  , 'Inner Mongolia Yili Industrial Group Co Ltd'                           ], 
    ['600893', '航发动力'  , 'AVIC AVIATION ENGINE CORPORATION PLC.'                                 ], 
    ['600900', '长江电力'  , 'China Yangtze Power Co Ltd'                                            ], 
    ['600919', '江苏银行'  , 'Bank of Jiangsu Co., Ltd'                                              ], 
    ['600926', '杭州银行'  , 'BANK OF HANGZHOU CO., LTD'                                             ], 
    ['600958', '东方证券'  , 'ORIENT SECURITIES COMPANY LIMITED'                                     ], 
    ['600977', '中国电影'  , 'CHINA FILM CO., LTD.'                                                  ], 
    ['600998', '九州通'   , 'Jointown Pharmaceutical Group Co Ltd'                                  ], 
    ['600999', '招商证券'  , 'China Merchants Securities Co Ltd'                                     ], 
    ['601006', '大秦铁路'  , 'Daqin Railway Co Ltd'                                                  ], 
    ['601009', '南京银行'  , 'Bank of Nanjing Co Ltd'                                                ], 
    ['601012', '隆基股份'  , 'Longi Green Energy Technology Co., Ltd.'                               ], 
    ['601018', '宁波港'   , 'Ningbo Port Co Ltd'                                                    ], 
    ['601021', '春秋航空'  , 'Spring Airlines Co., Ltd.'                                             ], 
    ['601088', '中国神华'  , 'China Shenhua Energy Co Ltd'                                           ], 
    ['601108', '财通证券'  , 'CAITONG SECURITIES CO.,LTD.'                                           ], 
    ['601111', '中国国航'  , 'Air China Ltd'                                                         ], 
    ['601117', '中国化学'  , 'China National Chemical Engineering Co Ltd'                            ], 
    ['601155', '新城控股'  , 'Future Land Holdings Co., Ltd.'                                        ], 
    ['601166', '兴业银行'  , 'Industrial Bank'                                                       ], 
    ['601169', '北京银行'  , 'Bank of Beijing Co Ltd'                                                ], 
    ['601186', '中国铁建'  , 'China Railway Construction Co Ltd'                                     ], 
    ['601198', '东兴证券'  , 'DONGXING SECURITIES CO., LTD.'                                         ], 
    ['601211', '国泰君安'  , 'Guotai Junan Securities Co., Ltd.'                                     ], 
    ['601212', '白银有色'  , 'Baiyin Nonferrous Group Co., Ltd.'                                     ], 
    ['601216', '君正集团'  , 'Inner Mongolia Junzheng Energy & Chemical Group Co.,Ltd.'              ], 
    ['601225', '陕西煤业'  , 'Shaanxi Coal Industry Company Limited'                                 ], 
    ['601229', '上海银行'  , 'Bank of Shanghai Co., Ltd.'                                            ], 
    ['601238', '广汽集团'  , 'Guangzhou Automobile Group Co., Ltd.'                                  ], 
    ['601288', '农业银行'  , 'Agricultural Bank of China Co Ltd'                                     ], 
    ['601318', '中国平安'  , 'Ping An Insurance (Group) Company of China Ltd'                        ], 
    ['601328', '交通银行'  , 'Bank of Communications Co LTD'                                         ], 
    ['601336', '新华保险'  , 'New China Life Insurance Co Ltd'                                       ], 
    ['601377', '兴业证券'  , 'Industrial Securities Co Ltd'                                          ], 
    ['601390', '中国中铁'  , 'China Railway Group Limited'                                           ], 
    ['601398', '工商银行'  , 'Industrial and Commercial Bank of China Ltd'                           ], 
    ['601555', '东吴证券'  , 'Soochow Securities Co Ltd'                                             ], 
    ['601600', '中国铝业'  , 'Aluminum Corporation of China Limited'                                 ], 
    ['601601', '中国太保'  , 'China Pacific Insurance (Group) Co Ltd'                                ], 
    ['601607', '上海医药'  , 'Shanghai Pharmaceuticals Holding Co.,Ltd'                              ], 
    ['601618', '中国中冶'  , 'Metallurgical Corporation of China Co Ltd'                             ], 
    ['601628', '中国人寿'  , 'China Life Insurance Company Limited'                                  ], 
    ['601633', '长城汽车'  , 'Great Wall Motor Co Ltd'                                               ], 
    ['601668', '中国建筑'  , 'China State Construction Engineering Co Ltd'                           ], 
    ['601669', '中国电建'  , 'Power Construction Corporation of China,Ltd'                           ], 
    ['601688', '华泰证券'  , 'Huatai Securities Co Ltd'                                              ], 
    ['601727', '上海电气'  , 'Shanghai Electric Group Co Ltd'                                        ], 
    ['601766', '中国中车'  , 'CRRC Corporation Limited'                                              ], 
    ['601788', '光大证券'  , 'Everbright Securities Co Ltd'                                          ], 
    ['601800', '中国交建'  , 'China Communications Construction Company Limited'                     ], 
    ['601808', '中海油服'  , 'China Oilfield Services Limited'                                       ], 
    ['601818', '光大银行'  , 'China Everbright Bank Co Ltd'                                          ], 
    ['601828', '美凯龙'   , 'Red Star Macalline Group Corporation Ltd.'                             ], 
    ['601838', '成都银行'  , 'BANK OF CHENGDU CO., LTD.'                                             ], 
    ['601857', '中国石油'  , 'PetroChina Co Ltd'                                                     ], 
    ['601877', '正泰电器'  , 'Zhejiang Chint Electrics Co Ltd'                                       ], 
    ['601878', '浙商证券'  , 'ZHESHANG SECURITIES CO., LTD.'                                         ], 
    ['601881', '中国银河'  , 'China Galaxy Securities Co., Ltd.'                                     ], 
    ['601888', '中国国旅'  , 'China International Travel Service Co Ltd'                             ], 
    ['601898', '中煤能源'  , 'China Coal Energy Co Ltd'                                              ], 
    ['601899', '紫金矿业'  , 'Zijin Mining Group Co Ltd'                                             ], 
    ['601901', '方正证券'  , 'Founder Securities Co Ltd'                                             ], 
    ['601919', '中远海控'  , 'COSCO SHIPPING Holdings Co., Ltd.'                                     ], 
    ['601933', '永辉超市'  , 'Yonghui Superstores Co Ltd'                                            ], 
    ['601939', '建设银行'  , 'China Construction Bank'                                               ], 
    ['601985', '中国核电'  , 'China National Nuclear Power Co.,Ltd.'                                 ], 
    ['601988', '中国银行'  , 'Bank of China Ltd'                                                     ], 
    ['601989', '中国重工'  , 'China Shipbuilding Industry Co Ltd'                                    ], 
    ['601992', '金隅股份'  , 'BBMG Corporation'                                                      ], 
    ['601997', '贵阳银行'  , 'Bank of Guiyang Co.,Ltd.'                                              ], 
    ['601998', '中信银行'  , 'China Citic Bank Corporation Limited'                                  ], 
    ['603019', '中科曙光'  , 'Dawning Information Industry Co., Ltd.'                                ], 
    ['603160', '汇顶科技'  , 'Shenzhen Huiding Technology Co., Ltd.'                                 ], 
    ['603260', '合盛硅业'  , 'HOSHINE SILICON INDUSTRY CO.,LTD'                                      ], 
    ['603288', '海天味业'  , 'Foshan Haitian Flavouring and Food Company Ltd.'                       ], 
    ['603501', '韦尔股份'  , 'Will Semiconductor CO.,Ltd. Shanghai'                                  ], 
    ['603799', '华友钴业'  , 'ZHEJIANG HUAYOU COBALT CO., LTD.'                                      ], 
    ['603833', '欧派家居'  , 'Oppein Home Group Inc.'                                                ], 
    ['603899', '晨光文具'  , 'SHANGHAI M&G STATIONERY INC.'                                          ], 
    ['603986', '兆易创新'  , 'GigaDevice Semiconductor (Beijing) Inc.'                               ], 
    ['603993', '洛阳钼业'  , 'China Molybdenum Co., Ltd.'                                            ], 
    ['000938', '紫光股份'  , 'Unisplendour Co., Ltd.'                                                ], 
    ['000630', '铜陵有色'  , 'Tongling Nonferrous Metals Group Co. Ltd'                              ], 
    ['002460', '赣锋锂业'  , 'Ganfeng Lithium Co Ltd'                                                ], 
    ['002466', '天齐锂业'  , 'Tianqi Lithium Industries, Inc.'                                       ], 
    ['000423', '东阿阿胶'  , 'Shandong Dong-Ee Jiao Co Ltd'                                          ], 
    ['000538', '云南白药'  , 'Yunnan Baiyao Group Co., Ltd.'                                         ], 
    ['002081', '金 螳 螂' , 'Suzhou Gold Mantis Construction Decoration Co Ltd'                     ], 
    ['002916', '深南电路'  , 'Shennan Circuits Co., Ltd.'                                            ], 
    ['000063', '中兴通讯'  , 'ZTE Corporation'                                                       ], 
    ['002044', '美年健康'  , 'Meinian Onehealth Healthcare Holdings Co., Ltd.'                       ], 
    ['002714', '牧原股份'  , 'Muyuan Foodstuff Co., Ltd'                                             ], 
    ['000786', '北新建材'  , 'Beijing New Building Materials Public Ltd Co'                          ], 
    ['002271', '东方雨虹'  , 'Beijing Oriental Yuhong Waterproof Technology Co Ltd'                  ], 
    ['002024', '苏宁云商'  , 'SUNING.COM CO.,LTD.'                                                   ], 
    ['002179', '中航光电'  , 'AVIC Jonhon Optronic Technology Co.,Ltd.'                              ], 
    ['002236', '大华股份'  , 'Zhejiang Dahua Technology Co Ltd'                                      ], 
    ['002241', '歌尔股份'  , 'GoerTek Inc'                                                           ], 
    ['002415', '海康威视'  , 'Hangzhou Hikvision Digital Technology Co Ltd'                          ], 
    ['002475', '立讯精密'  , 'Luxshare Precision Industry Co., Ltd.'                                 ], 
    ['000627', '天茂集团'  , 'Hubei Biocause Pharmaceutical Co Ltd'                                  ], 
    ['000703', '恒逸石化'  , 'Hengyi Petrochemical Co Ltd'                                           ], 
    ['002010', '传化智联'  , 'Transfar Zhilian Co.,Ltd.'                                             ], 
    ['002411', '必康股份'  , 'YanAn Bicon Pharmaceutical Listed Company'                             ], 
    ['002493', '荣盛石化'  , 'Rongsheng Petro Chemical Co Ltd'                                       ], 
    ['002601', '龙蟒佰利'  , 'Lomon Billions Group Co., Ltd.'                                        ], 
    ['002202', '金风科技'  , 'Xinjiang Goldwind Science & Technology Co Ltd'                         ], 
    ['000100', 'TCL 集团', 'TCL Technology Group Corporation'                                      ], 
    ['000333', '美的集团'  , 'Midea Group CO., LTD'                                                  ], 
    ['000651', '格力电器'  , 'Gree Electric Appliances,Inc. of Zhuhai'                               ], 
    ['002032', '苏 泊 尔' , 'Zhejiang Supor Co.,Ltd'                                                ], 
    ['002050', '三花智控'  , 'ZHEJIANG SANHUA INTELLIGENT CONTROLS CO.,LTD.'                         ], 
    ['002508', '老板电器'  , 'Hangzhou Robam Appliances Co Ltd'                                      ], 
    ['002555', '三七互娱'  , 'WUHU SANQI INTERACTIVE ENTERTAINMENT NETWORK TECHNOLOGY GROUP CO.,LTD.'], 
    ['002558', '巨人网络'  , 'Giant Network Group Co., Ltd.'                                         ], 
    ['002602', '世纪华通'  , 'ZHEJIANG CENTURY HUATONG GROUP CO., LTD'                               ], 
    ['002624', '完美世界'  , 'Perfect World Co., Ltd.'                                               ], 
    ['000895', '双汇发展'  , 'Henan Shuanghui Investment & Development Co Ltd'                       ], 
    ['000709', '河钢股份'  , 'HESTEEL COMPANY LIMITED'                                               ], 
    ['000898', '鞍钢股份'  , 'Angang Steel Co Ltd'                                                   ], 
    ['000661', '长春高新'  , 'Chang Chun High and New Technology Industry (Group) Inc.'              ], 
    ['002007', '华兰生物'  , 'Hualan Biological Engineering INC'                                     ], 
    ['002252', '上海莱士'  , 'Shanghai RAAS Blood Products Co Ltd'                                   ], 
    ['000166', '申万宏源'  , 'Shenwan Hongyuan Group CO., LTD'                                       ], 
    ['000728', '国元证券'  , 'Guoyuan Securities Company Limited'                                    ], 
    ['000776', '广发证券'  , 'GF Securities Co., Ltd.'                                               ], 
    ['000783', '长江证券'  , 'Changjiang Securities Company Limited'                                 ], 
    ['002673', '西部证券'  , 'WESTERN SECURITIES CO., LTD'                                           ], 
    ['002736', '国信证券'  , 'GUOSEN SECURITIES CO., LTD.'                                           ], 
    ['002120', '韵达股份'  , 'YUNDA Holding CO., Ltd.'                                               ], 
    ['002352', '顺丰控股'  , 'S.F. Holding Co., Ltd.'                                                ], 
    ['002468', '申通快递'  , 'STO Express Co.,Ltd.'                                                  ], 
    ['000415', '渤海金控'  , 'Bohai Leasing Co.,Ltd.'                                                ], 
    ['000629', '*ST钒钛' , 'Pangang Group Vanadium Titanium & Resources Co., Ltd.'                 ], 
    ['000338', '潍柴动力'  , 'Wei Chai Power Co Ltd'                                                 ], 
    ['000625', '长安汽车'  , 'Chongqing Changan Automobile Co Ltd'                                   ], 
    ['002594', '比亚迪'   , 'BYD Co Ltd'                                                            ], 
    ['002607', '亚夏汽车'  , 'Offcn Education Technology Co., Ltd.'                                  ], 
    ['000876', '新 希 望' , 'NEW HOPE LIUHE CO., LTD'                                               ], 
    ['002311', '海大集团'  , 'Guangdong Haid Group Co Ltd'                                           ], 
    ['002008', '大族激光'  , 'Han\'s Laser Technology Industry Group Co., Ltd.'                      ], 
    ['000963', '华东医药'  , 'Huadong Medicine Co Ltd'                                               ], 
    ['002001', '新 和 成' , 'Zhejiang NHU Co Ltd'                                                   ], 
    ['002294', '信立泰'   , 'Shenzhen Salubris Pharmaceuticals Co Ltd'                              ], 
    ['002422', '科伦药业'  , 'Sichuan Kelun Pharmaceutical Co Ltd'                                   ], 
    ['002773', '康弘药业'  , 'Chengdu Kanghong Pharmaceutical Group Co., Ltd'                        ], 
    ['000002', '万 科Ａ'  , 'China Vanke Co Ltd'                                                    ], 
    ['000069', '华侨城Ａ'  , 'Shenzhen Overseas Chinese Town Co Ltd'                                 ], 
    ['000656', '金科股份'  , 'Jinke Property Group Co.,Ltd.'                                         ], 
    ['000671', '阳 光 城' , 'Sunshine City Group Co., Ltd.'                                         ], 
    ['000961', '中南建设'  , 'Jiangsu Zhongnan Construction Group Co.,Ltd'                           ], 
    ['001979', '招商蛇口'  , 'CHINA MERCHANTS SHEKOU INDUSTRIAL ZONE HOLDINGS CO.,LTD'               ], 
    ['002146', '荣盛发展'  , 'Risesun Real Estate Development Co Ltd'                                ], 
    ['000768', '中航飞机'  , 'Avic Aircraft Co.,Ltd.'                                                ], 
    ['000568', '泸州老窖'  , 'Luzhou Lao Jiao Co Ltd'                                                ], 
    ['000596', '古井贡酒'  , 'Anhui Gujing Distillery Co Ltd'                                        ], 
    ['000858', '五 粮 液' , 'Wuliangye Yibin Co Ltd'                                                ], 
    ['002304', '洋河股份'  , 'Jiangsu Yanghe Brewery Joint-Stock Co Ltd'                             ], 
    ['000157', '中联重科'  , 'Zoomlion Heavy Industry Science & Technology Co Ltd'                   ], 
    ['000425', '徐工机械'  , 'XCMG Construction Machinery Co Ltd'                                    ], 
    ['002027', '分众传媒'  , 'Focus Media Information Technology Co., Ltd.'                          ], 
    ['002739', '万达电影'  , 'WANDA FILM HOLDING CO., LTD'                                           ], 
    ['000723', '美锦能源'  , 'Shanxi Meijin Energy Co.,Ltd.'                                         ], 
    ['002153', '石基信息'  , 'Beijing Shiji Information Technology Co Ltd'                           ], 
    ['002230', '科大讯飞'  , 'Iflytek Co.,Ltd.'                                                      ], 
    ['002410', '广联达'   , 'Glodon Software Co Ltd'                                                ], 
    ['000001', '平安银行'  , 'Ping An Bank Co., Ltd.'                                                ], 
    ['002142', '宁波银行'  , 'Bank of Ningbo Co Ltd'                                                 ], 
    ['000413', '东旭光电'  , 'Dongxu Optoelectronic Technology Co., Ltd.'                            ], 
    ['000725', '京东方Ａ'  , 'BOE Technology Group Co Ltd'                                           ], 
    ['002456', '欧菲科技'  , 'OFILM Group Co., Ltd.'                                                 ], 
    ['002841', '视源股份'  , 'Guangzhou Shiyuan Electronic Technology Company Limited'               ], 
  ], 
}